sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
    otherSprite.destroy()
    game.over(false, effects.slash)
})
game.splash("Go!")
info.setScore(0)
scene.setBackgroundImage(img`
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddddddeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeedddddddddddddddeeeeeeeeeeeeeeeddddddddddddddddddeeeeeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddddeeeeeeeeeeeeeeeeeeeeedddddddddddddeeeeeeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddeeeeeeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddeeeeeeeeeee.
    ddddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeedddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddeeeeeeeee...
    ddddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddeeeeeeeeeddddddddeeeeeeeeeeeeeedddddeeeeeeeeeeddddddddddddeeeeeeeeee..
    ddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddeeeeeeeeeedddddddeeeeeeeeeeeedddddddeeeeeeeeeeedddddddddddddddeeeeeeee.
    dddddddddddddddddddddddddddddddddddddddddddddfffffddddddddddddddddddddddddddddddddddddddeeeeeeeeeeedddddddeeeeeeeeeeeddddddddeeeeeeedddddddddddddddddddeeeeeeee.
    dddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeddddddeeeeeeeeeedddddddddeeeeeeedddddddddddddddddddddeeeeeee.
    ddddddddddddddddddddddeeeeeeeeeeeddddddddddddffffffdddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeddddddeeeeeeeedddddddddddeeeeeeeddddddddddddddddddddddeeeeeee
    ddddddddddddddddddddddeeeeeeeeeeeedddddddddddffffffdddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeedddddeeeeeeeeddddddddddddeeeeeeddddddddddddddddddddddddeeeeee
    ddddddddddddddddddddddeeeeeeeeeeeedddddddddddffffffdddddddddddddddddddddddddddddddeeeeeeeeeeedeeeeedddddeeeeeeeddddddddddddeeeeeeeddddddddddddddddddddddddeeeeee
    ddddddddddddddddddddddeeeeeeeeeeeeedddddddddddfffffddddddddddddddddddddddddddddddeeeeeeeeeeeddeeeeeedddeeeeeeedddddddddddddeeeeeedddddddddddddddddddddddddeeeeee
    ddddddddddddddddddddddeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeddddeeeeeedddeeeeeeeddddddddddddeeeeeeeddddddddddddddddddddddddddeeeee
    ddddddddddddddddddddddddddddeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeedddddeeeeeeeddeeeeeedddddddddddddeeeeeeeddddddddddddddddddddddddddeeeee
    dddddddddddddddddddddddddddddeeeeeeeeddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeddddddeeeeeeeddeeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddeeee
    dddddddddddddddddddddddddddddeeeeeeeeddddddddddddddddddddddddddddddddddddddddeeeeeeeeedddddddddeeeeeeedeeeeeeddddddddddddeeeeeeeddddddddddddddddddddddddddddeeee
    ddddddddddddddddddddddddddddddeeeeeeedddddddddddddddddddddddddddddddddddddddeeeeeeeeeddddddddddeeeeeeeeeeeeedddddddddddddeeeeeedddddddddddddddddddddddddddddeeee
    dddddddddddddddddddddddddddddddeeeeeedddddddddfffffdddddddddddddddddddddddddeeeeeeeeedddddddddddeeeeeeeeeeeedddddddddddddeeeeeedddddddddddddddddddddddddddddeeee
    ddddddddddddddddddddddddddddddddeeeeedddddddddfffffddddddddddddddddddddddddeeeeeeeeeddddddddddddeeeeeeeeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddeee
    ddddddddddddddddddddddddddddddddeeeeeeddddddddfffffdddddddddddddddddddddddeeeeeeeeeddddddddddddddeeeeeeeeeeeddddddddddddeeeeeedddddddddddddddddddddddddddddddeee
    ddddddddddddddddddddddddddddddddeeeeeeddddddddfffffdddddddddddddddddddddddeeeeeeedddddddddddddddddeeeeeeeeeeddddddddddddeeeeeedddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeeddddddddddddddeeeeeeddddddddfffffdfffffddddddddddddddddeeeeeeeedddddddddddddddddeeeeeeeeedddddddddddddeeeeeedddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeeddddddddddddddeeeeeeddddddddfffffdfffffdddddddddddddddeeeeeeeeddddddddddddddddddeeeeeeeeeddddddddddddeeeeeeedddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeedddddddddddddddeeeeeddddddddfffffdfffffdddddddddddddddeeeeeeeddddddddddddddddddddeeeeeeeeddddddddddddeeeeeeddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeedddddddddddddddeeeeeddddddddfffffdfffffdddddddddddddddeeeeeeeddddddddddddddddddddeeeeeeeeddddddddddddeeeeeeddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeedddddddddddddddeeeeeddddddddfffffffffffddddddddddddddeeeeeeeddddddddddddddddddddddeeeeeeeddddddddddddeeeeeeddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeeddddddddfffffffffffddddddddddddddeeeeeedddddddddddddddddddddddeeeeeeeddddddddddddeeeeedddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeeddddddddfffffffffffddddddddddddddeeeeeeddddddddddddddddddddddddeeeeeedddddddddddeeeeeedddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddddddddddeeeeeedddddddddddeeeeeedddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeeddddddddddddddddddddddddddddddddeeeeeedddddddddddddddddddddddddeeeeeedddddddddddeeeeeedddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeeddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddddddddddddeeeeeeddddddddddeeeeeedddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeeddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddddddddddddeeeeeedddddddddeeeeeeddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeddddddddddddddddddddddddddeeeeeedddddddddeeeeeeddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeedddddddddddddddeeeeeedddddddddfffffffffdddddddddddddeeeeeedddddddddddddddddddddddddddeeeeeeeddddddddeeeeeeddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeedddddddddddddddeeeeeedddddddddfffffffffdddddddddddddeeeeeeddddddddddddddddddddddddddddeeeeeeddddddddeeeeeeddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeedddddddddddddddeeeeeedddddddddffffffffddddddddddddddeeeeeeddddddddddddddddddddddddddddeeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeedddddddddddddeeeeeeedddddddddffffffffddddddddddddddeeeeedddddddddddddddddddddddddddddeeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeedddddddddddddeeeeeeddddddddddffffffffdddddddddddddeeeeeeddddddddddddddddddddddddddddddeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeeddddddddddddeeeeeeeddddddddddffffffffdddddddddddddeeeeeeddddddddddddddddddddddddddddddeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeee
    ddddddddddddeeeeeeddddddddddddeeeeeeeddddddddddffffffffdddddddddddddeeeeeeddddddddddddddddddddddddddddddeeeeedddddddeeeeeedddddddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeedddddddddddeeeeeeedddddddddddffffffffdddddddddddddeeeeeeddddddddddddddddddddddddddddddeeeeedddddddeeeeeedddddddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeeeddddddddeeeeeeeeeddddddddddfffffffffdddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeedddddddeeeeeedddddddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeeeeddddddeeeeeeeeedddddddddddffffffffddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeedddddddeeeeeedddddddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeeeeeddddeeeeeeeeeedddddddddddffffffffddddddddddddddeeeeeddddddddddddddddddddddddddddddeeeeeedddddddeeeeeddddddddddddddddddddddddddddddddddddeee
    dddddddddddddeeeeeeeeedeeeeeeeeeeeddddddddddddffffffffdddddddddddddddddddddddddddddddddddddddddddddddddeeeeeedddddddeeeeeddddddddddddddddddddddddddddddddddddeee
    ddddddddddddddeeeeeeeeeeeeeeeeeeedddddddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeedddddddeeeeeddddddddddddddddddddddddddddddddddddeee
    dddddddddddddddeeeeeeeeeeeeeeeedddddddddddddddfffffffddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeedddddddeeeeedddddddddddddddddddddddddddddddddddeeee
    dddddddddddddddeeeeeeeeeeeeeeeddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeeee
    dddddddddddddddddeeeeeeeeeeeedddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeddddddddeeeeedddddddddddddddddddddddddddddddddddeeee
    ddddddddddddddddddeeeeeeeeedddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeedddddddddeeeeedddddddddddddddddddddddddddddddddddeeee
    ddddddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeddddddddddeeeeedddddddddddddddddddddddddddddddddddeeee
    dddddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeedddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeee
    dddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeedddddddddddddeeeeedddddddddddddddddddddddddddddddddeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeddddddddddddddeeeeedddddddddddddddddddddddddddddddddeeeeee
    dddddddddddddddddddddddddddddddddddddddddddffffffffdddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeedddddddddddddddeeeeeddddddddddddddddddddddddddddddddeeeeeee
    dddddddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeddddddddddddddddeeeeeddddddddddddddddddddddddddddddddeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddddddddddddddddddddeeeeeeeeeeeedddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeed
    ddddddddddddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddddddddddddddddddddeeeeeeeeeedddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeed
    ddddddddddddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddddddddddddddddddddeeeeeeeddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddeeeeeeedd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeedddddddddddddddddddddddeeeeeeddddddddddddddddddddddddddddeeeeeeeedd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeddddddddddddddddddddddddeeeeeedddddddddddddddddddddddddeeeeeeeeeeddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeddddddddddddddddddddddddeeeeeeeddddddddddddddddddddddeeeeeeeeeeeeddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeddddddddddddddddddddddddeeeeeeeddddddddddddddddddddeeeeeeeeeeeeedddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeedddddddddddddddddeeeeeeeeeeeeeeedddd
    ddddddddddddddddddddddddddddddddddddddddffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeedddddddddddeeeeeeeeeeeeeeeeedddddd
    ddddddddddddddddddddddddddddddddddddddddffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeedddeeeeeeeeeeeeeeeeeeddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeeeeeddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddeeeeeeeeeeeeeddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddeeeeeeeddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddfffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    `)
let Cinder = sprites.create(img`
    . . . . . f f f f . . . . . 
    . . . f f 5 5 5 5 f f . . . 
    . . f 5 5 5 5 5 5 5 5 f . . 
    . f 5 5 5 5 5 5 5 5 5 5 f . 
    . f 5 5 5 d b b d 5 5 5 f . 
    f 5 5 5 b 4 4 4 4 b 5 5 5 f 
    f 5 5 c c 4 4 4 4 c c 5 5 f 
    f b b f b f 4 4 f b f b b f 
    f b b 4 1 f d d f 1 4 b b f 
    . f b f d d d d d d f b f . 
    . f 3 f e 4 4 4 4 e f 3 f . 
    . 3 3 f 6 9 9 9 9 6 f 3 3 . 
    . 2 d c 9 9 9 9 9 9 c d 2 . 
    . 2 f b 3 b 3 b 3 b b f 2 . 
    . . f f 3 b 3 b 3 3 f f . . 
    . . . . f f b b f f . . . . 
    `, SpriteKind.Player)
Cinder.say("AHHHH!!! The Lunar Queen!", 5000)
Cinder.setStayInScreen(true)
pause(5000)
Cinder.say("RUN!", 2000)
controller.moveSprite(Cinder)
pause(5000)
pause(1000)
let Lunar_Queen = sprites.create(img`
    . . . . . f f 4 4 f f . . . . . 
    . . . . f 5 4 5 5 4 5 f . . . . 
    . . . f e 4 5 5 5 5 4 e f . . . 
    . . f b 3 e 4 4 4 4 e 3 b f . . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 e b 3 e e 3 b e 3 3 f . 
    . f 3 3 f f e e e e f f 3 3 f . 
    . f b b f b f e e f b f b b f . 
    . f b b e 1 f 4 4 f 1 e b b f . 
    f f b b f 4 4 4 4 4 4 f b b f f 
    f b b f f f e e e e f f f b b f 
    . f e e f b d d d d b f e e f . 
    . . e 4 c d d d d d d c 4 e . . 
    . . e f b d b d b d b b f e . . 
    . . . f f 1 d 1 d 1 d f f . . . 
    . . . . . f f b b f f . . . . . 
    `, SpriteKind.Projectile)
Lunar_Queen.setStayInScreen(true)
Lunar_Queen.follow(Cinder, 20)
forever(function () {
    if (game.runtime() >= 100000) {
        game.over(true, effects.confetti)
    }
    pause(5000)
    info.changeScoreBy(1)
})
